variables:
  GIT_SSL_NO_VERIFY: "true"
  CI_REGISTRY_USER: "sonar-runner"
  MAVEN_OPTS: "-Dmaven.repo.local=/dependencias-m2/.m2/repository"
  MAVEN_CLI_OPTS: "-s /dependencias-m2/.m2/dev-settings.xml --batch-mode"

  SECURE_ANALYZERS_PREFIX: "registry.gitlab.telconet.ec/docker/images/spotbugs"
  SAST_DEFAULT_ANALYZERS: "spotbugs"
  SAST_EXCLUDED_PATHS: "spec, test, tests, tmp"
  SCAN_KUBERNETES_MANIFESTS: "false"
  SAST_JAVA_VERSION: 8

stages:
  - VALIDATION
  - BUILD
  - SCAN BUILD VULNERABILITIES
  - MERGE

include:
  - template: dev-validation-microservicio.gitlab-ci.yml
  - template: dev-sonar.gitlab-ci.yml
  - template: dev-scan-vulnerabilities-java.gitlab-ci.yml
  - template: scan-dependencies-java.gitlab-ci.yml
  - template: microservicio-test-build.gitlab-ci.yml
  - template: microservicio-prod-build.gitlab-ci.yml
  - template: dependencia-prod-merge.gitlab-ci.yml
