variables:
  GIT_SSL_NO_VERIFY: "true"
  CI_REGISTRY_USER: "sonar-runner"
  MAVEN_OPTS: "-Dmaven.repo.local=/dependencias-m2/.m2/repository"
  MAVEN_CLI_OPTS: "-s /dependencias-m2/.m2/dev-settings.xml --batch-mode"

  SECURE_ANALYZERS_PREFIX: "registry.gitlab.telconet.ec/docker/images/spotbugs"
  SAST_DEFAULT_ANALYZERS: "spotbugs"
  SAST_EXCLUDED_PATHS: "spec, test, tests, tmp"
  SCAN_KUBERNETES_MANIFESTS: "false"
  SECURE_LOG_LEVEL: "debug"
  SAST_JAVA_VERSION: 8

stages:
  - VALIDATION
  - QUALITY CODE
  - SCAN DEV VULNERABILITIES
  - BUILD
  - MERGE

include:
  - template: dev-validation-microservicio-v1.gitlab-ci.yml
  - template: dev-sonar-v1.gitlab-ci.yml
  - template: dev-build-v1.gitlab-ci.yml
  - template: dev-scan-vulnerabilities-java-v1.gitlab-ci.yml
  - template: dev-scan-dependencies-java-v1.gitlab-ci.yml
  - template: microservicio-test-build-v1.gitlab-ci.yml
  - template: microservicio-prod-build-v1.gitlab-ci.yml
  - template: dependencia-prod-merge-v1.gitlab-ci.yml
