image: docker:stable                          

variables:
  DOCKER_DRIVER: overlay2
  GIT_SSL_NO_VERIFY: "true"
  CI_REGISTRY_USER: "sonar-runner"
  CI_RUTA_FILE: ""
  CI_VERSION: ""
  IP: ""

stages:
  - SONAR
  - DEV
  - QA
  - PROD

include:
  - template: sonar-scanner.gitlab-ci.yml
  - template: microservice-build-microdev.gitlab-ci.yml
  - template: artifactory-scripts-microdev.gitlab-ci.yml
  - template: microservice-build-microqams.gitlab-ci.yml
  - template: artifactory-scripts-microsqa.gitlab-ci.yml
  - template: microservice-build-microprd.gitlab-ci.yml
  - template: artifactory-scripts-micro-prod.gitlab-ci.yml
  - template: merge-prod.gitlab-ci.yml
