variables:
  GIT_SSL_NO_VERIFY: "true"
  CI_REGISTRY_USER: "sonar-runner"
  MAVEN_OPTS: "-Dmaven.repo.local=/dependencias-m2/.m2/repository"
  MAVEN_CLI_OPTS: "-s /dependencias-m2/.m2/dev-settings.xml --batch-mode"

  SECURE_ANALYZERS_PREFIX: "registry.gitlab.telconet.ec/docker/images/spotbugs"
  SAST_DEFAULT_ANALYZERS: "spotbugs"
  SAST_EXCLUDED_PATHS: "spec, test, tests, tmp"
  SCAN_KUBERNETES_MANIFESTS: "false"
  SECURE_LOG_LEVEL: "debug"
  SAST_JAVA_VERSION: 8

stages:
  - VALIDATION
  - QUALITY CODE
  - SCAN DEV VULNERABILITIES
  - BUILD
  - MERGE

include:
  - template: sis-docker-validacion-microservicio.gitlab-ci.yml
  - template: sis-docker-sonar-microservicio.gitlab-ci.yml
  - template: sis-docker-build-microservicio.gitlab-ci.yml
  - template: sis-docker-scan-vulnerabilities-java.gitlab-ci.yml
  - template: sis-docker-scan-dependencies-java.gitlab-ci.yml
  - template: sis-docker-build-test-microservicio.gitlab-ci.yml
  - template: sis-docker-build-prod-microservicio.gitlab-ci.yml
  - template: sis-docker-prod-merge-dependencia.gitlab-ci.yml
